-- LEFT JOIN 
SELECT NAME,ROLL_NUM,MARKS FROM STUDENTS S
LEFT JOIN MARKS_RESULT M
ON S.ROLL_NUM=M.HALL_TICKIT_NUMBER;

-- RIGHT JOIN
SELECT * FROM STUDENTS S
RIGHT JOIN MARKS_RESULT M
ON S.ROLL_NUM=M.HALL_TICKIT_NUMBER;


-- INNER JOIN
SELECT * FROM STUDENTS S
INNER JOIN MARKS_RESULT M
ON S.ROLL_NUM=M.HALL_TICKIT_NUMBER;

-- FULL/OUTER JOIN
SELECT * FROM STUDENTS S
LEFT JOIN MARKS_RESULT M
ON S.ROLL_NUM=M.HALL_TICKIT_NUMBER
UNION 
SELECT * FROM STUDENTS S
RIGHT JOIN MARKS_RESULT M
ON S.ROLL_NUM=M.HALL_TICKIT_NUMBER;

-- CROSS JOIN(WITH THE HEP OF CROSS JOIN METHOD)
SELECT * FROM STUDENTS
CROSS JOIN MARKS_RESULT;

-- CROSS JOIN(WITH THE HELP OF DIRECT METHOD)
SELECT * FROM STUDENTS,MARKS_RESULT;

-- EXCLUSIVE LEFT JOIN
SELECT * FROM STUDENTS S
LEFT JOIN MARKS_RESULT M
ON S.ROLL_NUM=M.HALL_TICKIT_NUMBER
WHERE M.HALL_TICKIT_NUMBER IS NULL;

-- EXCLUSIVE RIGHT JOIN
SELECT * FROM STUDENTS S
RIGHT JOIN MARKS_RESULT M
ON S.ROLL_NUM=M.HALL_TICKIT_NUMBER
WHERE S.ROLL_NUM IS NULL;

UPDATE STUDENTS
SET TEACHER_ID=2 WHERE ROLL_NUM IN(3,4) ;
UPDATE STUDENTS
SET TEACHER_ID=3 WHERE ROLL_NUM IN(1,2);

UPDATE STUDENTS SET NUMBER_COURSES=2 WHERE ROLL_NUM IN(3,2);
UPDATE STUDENTS SET NUMBER_COURSES=1 WHERE ROLL_NUM NOT IN(3,2);

-- SELF JOIN

SELECT B.NAME AS TEACHER_NAME,S.NAME AS STUDENT_NAME,S.NUMBER_COURSES FROM STUDENTS S
JOIN STUDENTS B
ON S.TEACHER_ID=B.ROLL_NUM
ORDER BY NUMBER_COURSES DESC;
