-- GROUP BY AND HAVING

SELECT * FROM STUDENTS;
SELECT* FROM MARKS_RESULT;

-- MAX NUMBER CURSES STUDENT NAME
SELECT NAME,MAX(NUMBER_COURSES) FROM STUDENTS
GROUP BY NAME
HAVING MAX(NUMBER_COURSES)>=2;

-- MIN NUMBER CURSES STUDENT NAME
SELECT NAME, MIN(NUMBER_COURSES) FROM STUDENTS
GROUP BY NAME
HAVING MIN(NUMBER_COURSES)< 2;

