SELECT NAME FROM STUDENTS
WHERE ROLL_NUM IN (
SELECT HALL_TICKIT_NUMBER FROM MARKS_RESULT
WHERE MARKS>(SELECT AVG(MARKS) FROM MARKS_RESULT)
);

-- LESS THAN HIGHEST MARKS
SELECT S.NAME,B.MARKS FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER
WHERE MARKS<(SELECT MAX(MARKS) FROM MARKS_RESULT);

-- HIGHEST MARKS
SELECT S.NAME,B.MARKS FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER
WHERE MARKS=(SELECT MAX(MARKS) FROM MARKS_RESULT);

-- 2ND HIGHEST MARKS
SELECT S.NAME,B.MARKS FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER
WHERE MARKS IN (SELECT MAX(MARKS) FROM MARKS_RESULT
WHERE MARKS NOT IN (SELECT MAX(MARKS) FROM MARKS_RESULT));

SELECT S.NAME,B.MARKS FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER
WHERE MARKS IN (SELECT MIN(MARKS) FROM MARKS_RESULT);



SELECT * FROM STUDENTS;
SELECT * FROM MARKS_RESULT;

-- Which teacher has maximum students?
SELECT B.NAME AS TEACHER,COUNT(S.ROLL_NUM) AS STUDENT_COUNT FROM STUDENTS S
JOIN STUDENTS B
ON S.TEACHER_ID=B.ROLL_NUM
GROUP BY B.NAME
HAVING COUNT(S.ROLL_NUM) = (SELECT MAX(COUNTS)
                            FROM (
                            SELECT COUNT(S2.ROLL_NUM) AS COUNTS FROM STUDENTS S2
                            JOIN STUDENTS B2
                            ON S2.TEACHER_ID=B2.ROLL_NUM
                            GROUP BY B2.NAME
                            )AS SUB
);

-- Which teacher has more than 1 student?
SELECT B.NAME AS STU_MORE_THAN_1, COUNT(S.ROLL_NUM) FROM STUDENTS AS S
JOIN STUDENTS B
ON S.TEACHER_ID=B.ROLL_NUM
GROUP BY B.NAME
HAVING COUNT(S.ROLL_NUM)>1;

-- Total students per teacher (with name)
SELECT COUNT(S.ROLL_NUM) AS TOTAL_STUDENT, B.NAME AS PER_TEACHER FROM STUDENTS S
JOIN STUDENTS B
ON S.TEACHER_ID=B.ROLL_NUM
GROUP BY B.NAME;

-- Find the teacher(s) who have the maximum number of students. If there is a tie, return all such teachers.
SELECT * FROM STUDENTS;
SELECT TEACHER_ID,COUNT(ROLL_NUM) AS MAX_COUNT_STUDENT FROM STUDENTS AS TOTAL_COUNT
GROUP BY TEACHER_ID
HAVING COUNT(ROLL_NUM) = (SELECT MAX(STUDENT_COUNT) FROM 
                          (SELECT COUNT(ROLL_NUM) AS STUDENT_COUNT FROM STUDENTS
                           GROUP BY TEACHER_ID
                          ) AS TEMP
);