-- Lowest, higest, avg,total marks per teacher 
SELECT S.NAME,S.TEACHER_ID,B.MARKS,
MIN(B.MARKS) OVER(PARTITION BY S.TEACHER_ID) AS MIN_MARKS,
MAX(B.MARKS) OVER(PARTITION BY S.TEACHER_ID) AS MAX_MARKS,
AVG(B.MARKS) OVER(PARTITION BY S.TEACHER_ID) AS AVG_MARKS,
SUM(B.MARKS) OVER(PARTITION BY S.TEACHER_ID) AS TOTAL_SUM_MARKS
FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER;

-- 2nd highest per teacher (handle ties properly)
SELECT * FROM
(SELECT S.NAME,S.TEACHER_ID,B.MARKS,
DENSE_RANK() OVER(PARTITION BY S.TEACHER_ID ORDER BY B.MARKS DESC) AS STUDENT_RANK
FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER) T
WHERE STUDENT_RANK =2;

-- Find gap between top 2 students 
SELECT * FROM
(SELECT ROLL_NUM, NAME,TEACHER_ID,MARKS,RNK,ABS(MARKS-LAG_MARKS) AS GAP_MARKS
FROM
(SELECT ROLL_NUM, NAME,TEACHER_ID,MARKS,RNK,
LAG(MARKS) OVER(PARTITION BY TEACHER_ID ORDER BY MARKS DESC) AS LAG_MARKS
FROM 
(SELECT S.ROLL_NUM,S.NAME,S.TEACHER_ID,B.MARKS,
DENSE_RANK() OVER(PARTITION BY S.TEACHER_ID ORDER BY B.MARKS DESC) AS RNK
FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER)T1
)T2
)T
WHERE T.RNK= 2;

SELECT *,
LAG(B.MARKS) OVER(PARTITION BY S.TEACHER_ID ORDER BY B.MARKS) AS LAG_MARKS
FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM = B.HALL_TICKIT_NUMBER;

SELECT *,
LEAD(MARKS) OVER(ORDER BY MARKS) AS LEAD_MARKS
FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM = B.HALL_TICKIT_NUMBER;