-- ABOVE AVG AND BELOW AVG MARKS PER STUDENTS BY GROUPING TEACHER_ID
SELECT S.NAME AS STUDENT_NAME,B.MARKS,S.TEACHER_ID,
CASE WHEN B.MARKS>AVG(B.MARKS) OVER(PARTITION BY S.TEACHER_ID)
THEN 'ABOVE AVERAGE'
ELSE 'BELOW AVERAGE' 
END AS MARKS_STATUS
FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM = B.HALL_TICKIT_NUMBER;