
-- Which teacher teaches students with highest average marks?

SELECT T.TEACHER_ID AS TEACHER_NAME,T.MARKS AS MARKS,T.NAME AS STUDENT_NAME 
FROM 
(SELECT S.NAME,B.MARKS,S.TEACHER_ID
FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER
WHERE B.MARKS > (SELECT AVG(MARKS) FROM MARKS_RESULT)) AS T;


-- Which teacher teaches students with highest average marks?
SELECT * FROM STUDENTS;
SELECT* FROM MARKS_RESULT;

SELECT B.NAME AS TEACHERS_NAME,AVG(M.MARKS) AS highest_average FROM STUDENTS S
JOIN STUDENTS B
ON S.TEACHER_ID=B.ROLL_NUM
JOIN MARKS_RESULT M
ON S.ROLL_NUM=M.HALL_TICKIT_NUMBER
GROUP BY B.NAME
HAVING AVG(M.MARKS) IN (SELECT MARKS FROM MARKS_RESULT
         WHERE MARKS>(SELECT AVG(MARKS) FROM MARKS_RESULT));

-- Rank inside each teacher group
SELECT * FROM STUDENTS;
SELECT* FROM MARKS_RESULT;

SELECT S.NAME AS STUDENT_NAME,B.NAME AS TEACHER_NAME,M.MARKS,
DENSE_RANK() OVER(PARTITION BY B.NAME ORDER BY M.MARKS DESC) AS TEACHERS_GROUP_RANK
FROM STUDENTS S
JOIN STUDENTS B
ON S.TEACHER_ID=B.ROLL_NUM
JOIN MARKS_RESULT M
ON S.ROLL_NUM=M.HALL_TICKIT_NUMBER;

-- Find students whose marks are,above overall average BUT below teacher average
SELECT * FROM STUDENTS;
SELECT* FROM MARKS_RESULT;

 SELECT * FROM
 (SELECT S.NAME,B.MARKS,S.TEACHER_ID,
 AVG(B.MARKS) OVER(PARTITION BY S.TEACHER_ID) AS TEACHES_AVG,
 (SELECT AVG(MARKS) FROM MARKS_RESULT) AS OVERALL_AVG
 FROM STUDENTS S
 JOIN MARKS_RESULT B
 ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER)T
 
WHERE T.MARKS>OVERALL_AVG
AND T.MARKS<TEACHES_AVG;
 
-- Find students who scored:
-- above their teacher’s average marks BUT below overall average marks

SELECT * FROM STUDENTS;
SELECT* FROM MARKS_RESULT;
 
 SELECT * FROM
 (
 SELECT S.NAME AS STUDENTS_NAME,B.MARKS AS MARKS,S.TEACHER_ID, AVG(B.MARKS) OVER(PARTITION BY S.TEACHER_ID) AS TEACHERS_AVG_MARKS,(SELECT AVG(MARKS) FROM MARKS_RESULT) AS OVERALL_AVG_MARKS,
 CASE 
 WHEN B.MARKS > AVG(B.MARKS) OVER(PARTITION BY S.TEACHER_ID) THEN 'STUDENTS_MARKS_ABOVE_THAN_TEACHER_AVG_MARKS'
 WHEN B.MARKS < (SELECT AVG(MARKS) FROM MARKS_RESULT) THEN 'STUDENTS_MARKS_LESSER_THAN_OVERALL_AVG_MARKS'
 END AS STUDENTS_STATUS
 FROM STUDENTS S
 JOIN MARKS_RESULT B
 ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER) T
 WHERE T.MARKS > T.TEACHERS_AVG_MARKS
 AND T.MARKS < T.OVERALL_AVG_MARKS;
 
 -- Find students who are in top 2 marks of their teacher group AND their marks are above overall average
SELECT * FROM STUDENTS;
SELECT* FROM MARKS_RESULT;
SELECT * FROM
(SELECT S.NAME AS STUDENT_NAME,B.MARKS,S.TEACHER_ID,DENSE_RANK() OVER(PARTITION BY TEACHER_ID ORDER BY B.MARKS DESC) AS RANK_WITHIN_TEACHER_GROUP,(SELECT AVG(MARKS) FROM MARKS_RESULT) AS OVERALL_AVG_MARKS
FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER) T
WHERE
T.RANK_WITHIN_TEACHER_GROUP<=2
AND
T.MARKS>T.OVERALL_AVG_MARKS;

-- Show difference between current student's marks next student's marks

SELECT * FROM STUDENTS;
SELECT* FROM MARKS_RESULT;

SELECT S.NAME,B.MARKS AS CURRENT_STUDENT_MARKS, LEAD(B.MARKS) OVER() AS NEXT_MARKS, (LEAD(B.MARKS) OVER() - B.MARKS) AS MARKS_DIFF
FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER;

-- Create performance buckets:
-- Topper
-- Average
-- Weak
-- based on rank per teacher.

SELECT * FROM STUDENTS;
SELECT* FROM MARKS_RESULT;

SELECT *,
CASE 
WHEN T.rank_per_teacher=1 THEN 'Topper'
WHEN T.rank_per_teacher=2 THEN 'Average'
ELSE 'Weak'
END performance_bucket
FROM
(SELECT S.NAME,B.MARKS,DENSE_RANK() OVER(PARTITION BY TEACHER_ID ORDER BY B.MARKS DESC) AS rank_per_teacher
FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER) T;