USE join_practice;
CREATE TABLE STUDENTS(
NAME VARCHAR(255) NOT NULL,
ROLL_NUM INT PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE MARKS_RESULT(
HALL_TICKIT_NUMBER INT PRIMARY KEY,
MARKS DECIMAL(5,2),
CONSTRAINT FK_ID FOREIGN KEY(HALL_TICKIT_NUMBER) REFERENCES STUDENTS(ROLL_NUM)
);

;INSERT INTO STUDENTS(NAME)
VALUES 
('JAMES'),
('CARRY'),
('SMITH'),
('KENNI');

SELECT * FROM STUDENTS;

INSERT INTO MARKS_RESULT(HALL_TICKIT_NUMBER,MARKS)
VALUES
(1,45.90),
(2,69.90),
(3,90.00);
SELECT * FROM MARKS_RESULT;

-- LEFT JOIN 
SELECT NAME,ROLL_NUM,MARKS FROM STUDENTS S
LEFT JOIN MARKS_RESULT M
ON S.ROLL_NUM=M.HALL_TICKIT_NUMBER;

-- RIGHT JOIN
SELECT * FROM STUDENTS S
RIGHT JOIN MARKS_RESULT M
ON S.ROLL_NUM=M.HALL_TICKIT_NUMBER;


-- INNER JOIN
SELECT * FROM STUDENTS S
INNER JOIN MARKS_RESULT M
ON S.ROLL_NUM=M.HALL_TICKIT_NUMBER;

-- FULL/OUTER JOIN
SELECT * FROM STUDENTS S
LEFT JOIN MARKS_RESULT M
ON S.ROLL_NUM=M.HALL_TICKIT_NUMBER
UNION 
SELECT * FROM STUDENTS S
RIGHT JOIN MARKS_RESULT M
ON S.ROLL_NUM=M.HALL_TICKIT_NUMBER;

-- CROSS JOIN(WITH THE HEP OF CROSS JOIN METHOD)
SELECT * FROM STUDENTS
CROSS JOIN MARKS_RESULT;

-- CROSS JOIN(WITH THE HELP OF DIRECT METHOD)
SELECT * FROM STUDENTS,MARKS_RESULT;

-- EXCLUSIVE LEFT JOIN
SELECT * FROM STUDENTS S
LEFT JOIN MARKS_RESULT M
ON S.ROLL_NUM=M.HALL_TICKIT_NUMBER
WHERE M.HALL_TICKIT_NUMBER IS NULL;

-- EXCLUSIVE RIGHT JOIN
SELECT * FROM STUDENTS S
RIGHT JOIN MARKS_RESULT M
ON S.ROLL_NUM=M.HALL_TICKIT_NUMBER
WHERE S.ROLL_NUM IS NULL;


-- SELF JOIN 
ALTER TABLE STUDENTS
ADD TEACHER_ID INT;
ALTER TABLE STUDENTS
ADD NUMBER_COURSES INT;

UPDATE STUDENTS
SET TEACHER_ID=2 WHERE ROLL_NUM IN(3,4) ;
UPDATE STUDENTS
SET TEACHER_ID=3 WHERE ROLL_NUM IN(1,2);

UPDATE STUDENTS SET NUMBER_COURSES=2 WHERE ROLL_NUM IN(3,2);
UPDATE STUDENTS SET NUMBER_COURSES=1 WHERE ROLL_NUM NOT IN(3,2);

-- SELF JOIN

SELECT B.NAME AS TEACHER_NAME,S.NAME AS STUDENT_NAME,S.NUMBER_COURSES FROM STUDENTS S
JOIN STUDENTS B
ON S.TEACHER_ID=B.ROLL_NUM
ORDER BY NUMBER_COURSES DESC;

-- GROUP BY AND HAVING

SELECT * FROM STUDENTS;
SELECT* FROM MARKS_RESULT;

-- MAX NUMBER CURSES STUDENT NAME
SELECT NAME,MAX(NUMBER_COURSES) FROM STUDENTS
GROUP BY NAME
HAVING MAX(NUMBER_COURSES)>=2;

-- MIN NUMBER CURSES STUDENT NAME
SELECT NAME, MIN(NUMBER_COURSES) FROM STUDENTS
GROUP BY NAME
HAVING MIN(NUMBER_COURSES)< 2;


-- SUBQUERIES
SELECT NAME FROM STUDENTS
WHERE ROLL_NUM IN (
SELECT HALL_TICKIT_NUMBER FROM MARKS_RESULT
WHERE MARKS>(SELECT AVG(MARKS) FROM MARKS_RESULT)
);

-- LESS THAN HIGHEST MARKS
SELECT S.NAME,B.MARKS FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER
WHERE MARKS<(SELECT MAX(MARKS) FROM MARKS_RESULT);

-- HIGHEST MARKS
SELECT S.NAME,B.MARKS FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER
WHERE MARKS=(SELECT MAX(MARKS) FROM MARKS_RESULT);

-- 2ND HIGHEST MARKS
SELECT S.NAME,B.MARKS FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER
WHERE MARKS IN (SELECT MAX(MARKS) FROM MARKS_RESULT
WHERE MARKS NOT IN (SELECT MAX(MARKS) FROM MARKS_RESULT));

SELECT S.NAME,B.MARKS FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER
WHERE MARKS IN (SELECT MIN(MARKS) FROM MARKS_RESULT);



SELECT * FROM STUDENTS;
SELECT * FROM MARKS_RESULT;

-- Which teacher has maximum students?
SELECT B.NAME AS TEACHER,COUNT(S.ROLL_NUM) AS STUDENT_COUNT FROM STUDENTS S
JOIN STUDENTS B
ON S.TEACHER_ID=B.ROLL_NUM
GROUP BY B.NAME
HAVING COUNT(S.ROLL_NUM) = (SELECT MAX(COUNTS)
                            FROM (
                            SELECT COUNT(S2.ROLL_NUM) AS COUNTS FROM STUDENTS S2
                            JOIN STUDENTS B2
                            ON S2.TEACHER_ID=B2.ROLL_NUM
                            GROUP BY B2.NAME
                            )AS SUB
);

-- Which teacher has more than 1 student?
SELECT B.NAME AS STU_MORE_THAN_1, COUNT(S.ROLL_NUM) FROM STUDENTS AS S
JOIN STUDENTS B
ON S.TEACHER_ID=B.ROLL_NUM
GROUP BY B.NAME
HAVING COUNT(S.ROLL_NUM)>1;

-- Total students per teacher (with name)
SELECT COUNT(S.ROLL_NUM) AS TOTAL_STUDENT, B.NAME AS PER_TEACHER FROM STUDENTS S
JOIN STUDENTS B
ON S.TEACHER_ID=B.ROLL_NUM
GROUP BY B.NAME;

-- Find the teacher(s) who have the maximum number of students. If there is a tie, return all such teachers.
SELECT * FROM STUDENTS;
SELECT TEACHER_ID,COUNT(ROLL_NUM) AS MAX_COUNT_STUDENT FROM STUDENTS AS TOTAL_COUNT
GROUP BY TEACHER_ID
HAVING COUNT(ROLL_NUM) = (SELECT MAX(STUDENT_COUNT) FROM 
                          (SELECT COUNT(ROLL_NUM) AS STUDENT_COUNT FROM STUDENTS
                           GROUP BY TEACHER_ID
                          ) AS TEMP
);



SELECT * FROM STUDENTS;
SELECT* FROM MARKS_RESULT;

-- Lowest, higest, avg,total marks per teacher 
SELECT S.NAME,S.TEACHER_ID,B.MARKS,
MIN(B.MARKS) OVER(PARTITION BY S.TEACHER_ID) AS MIN_MARKS,
MAX(B.MARKS) OVER(PARTITION BY S.TEACHER_ID) AS MAX_MARKS,
AVG(B.MARKS) OVER(PARTITION BY S.TEACHER_ID) AS AVG_MARKS,
SUM(B.MARKS) OVER(PARTITION BY S.TEACHER_ID) AS TOTAL_SUM_MARKS
FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER;

-- 2nd highest per teacher (handle ties properly)
SELECT * FROM
(SELECT S.NAME,S.TEACHER_ID,B.MARKS,
DENSE_RANK() OVER(PARTITION BY S.TEACHER_ID ORDER BY B.MARKS DESC) AS STUDENT_RANK
FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER) T
WHERE STUDENT_RANK =2;

-- Find gap between top 2 students 
SELECT * FROM
(SELECT ROLL_NUM, NAME,TEACHER_ID,MARKS,RNK,ABS(MARKS-LAG_MARKS) AS GAP_MARKS
FROM
(SELECT ROLL_NUM, NAME,TEACHER_ID,MARKS,RNK,
LAG(MARKS) OVER(PARTITION BY TEACHER_ID ORDER BY MARKS DESC) AS LAG_MARKS
FROM 
(SELECT S.ROLL_NUM,S.NAME,S.TEACHER_ID,B.MARKS,
DENSE_RANK() OVER(PARTITION BY S.TEACHER_ID ORDER BY B.MARKS DESC) AS RNK
FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER)T1
)T2
)T
WHERE T.RNK= 2;

SELECT *,
LAG(B.MARKS) OVER(PARTITION BY S.TEACHER_ID ORDER BY B.MARKS) AS LAG_MARKS
FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM = B.HALL_TICKIT_NUMBER;

SELECT *,
LEAD(MARKS) OVER(ORDER BY MARKS) AS LEAD_MARKS
FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM = B.HALL_TICKIT_NUMBER;

-- ABOVE AVG AND BELOW AVG MARKS PER STUDENTS BY GROUPING TEACHER_ID
SELECT S.NAME AS STUDENT_NAME,B.MARKS,S.TEACHER_ID,
CASE WHEN B.MARKS>AVG(B.MARKS) OVER(PARTITION BY S.TEACHER_ID)
THEN 'ABOVE AVERAGE'
ELSE 'BELOW AVERAGE' 
END AS MARKS_STATUS
FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM = B.HALL_TICKIT_NUMBER;




















