-- CTE
-- Find students whose marks are greater than previous student marks but less than next student marks

SELECT * FROM STUDENTS;
SELECT* FROM MARKS_RESULT;

WITH TEMP AS(
SELECT S.NAME AS STUDENT_NAME,B.MARKS AS CURRENT_MARKS, LAG(B.MARKS) OVER(ORDER BY B.MARKS) AS PREVIOUS_MARKS,LEAD(B.MARKS) OVER(ORDER BY B.MARKS) AS NEXT_MARKS 
FROM STUDENTS S
JOIN MARKS_RESULT B
ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER
)
SELECT * FROM TEMP
WHERE
CURRENT_MARKS>PREVIOUS_MARKS
AND 
CURRENT_MARKS<NEXT_MARKS;

--  Find teacher-wise toppers only BUT Show only those toppers whose marks are also above overall average.

SELECT * FROM STUDENTS;
SELECT* FROM MARKS_RESULT;
WITH REPORT AS
(
SELECT S2.NAME AS TEACHER_NAME, S.NAME AS STUDENT_NAME, B.MARKS AS MARKS, DENSE_RANK() OVER(PARTITION BY S2.NAME ORDER BY B.MARKS DESC) AS TEACHER_WISE_RANK, 
(SELECT AVG(MARKS) FROM MARKS_RESULT) AS OVERALL_AVERAGE
FROM STUDENTS S
JOIN STUDENTS S2
ON S.TEACHER_ID=S2.ROLL_NUM
JOIN MARKS_RESULT B
ON S.ROLL_NUM=B.HALL_TICKIT_NUMBER
)
SELECT *,
CASE REPORT.TEACHER_WISE_RANK
WHEN 1 THEN 'TOPPER'
WHEN 2 THEN 'AVERAGE'
ELSE 'WEAK'
END PERFORMANCE
FROM REPORT
WHERE
TEACHER_WISE_RANK = 1
AND
MARKS > OVERALL_AVERAGE